### ISSUE TITLE
Where is the file 'deletion.yml'?

### ISSUE THREAD

**Issue by shanpoyang654** [Vaidehi99/InfoDeletionAttacks#1]
Hi, Vaidehi Patil!
Thanks for your effort!

I'm wondering where is the file 'deletion.yml' in the command 'conda env create -f deletion.yml'.

Looking forward to your response and continuation of our work. Thank you for your attention to this matter.

**Comment by Vaidehi99** [comment]
Hi, thanks for you interest in the work. [Here](https://github.com/Vaidehi99/InfoDeletionAttacks/blob/main/deletion.yml) is the file.
