### ISSUE TITLE
 'rephrases = pickle.load(open("","rb"))' doesn't have a file_path.

### ISSUE THREAD

**Issue by shanpoyang654** [Vaidehi99/InfoDeletionAttacks#2]
Hi,
I find that in '/third_party/rome/compute_v.py', this code 'rephrases = pickle.load(open("","rb"))' doesn't have a file_path.
So i can't execute it.
Is that correct?
Thanks!

**Comment by Vaidehi99** [comment]
Hi, thanks for your interest in the work. I have modified the script to include the missing path.
